import { links, avatars } from './imageLinks';
export const dummyUsers = [
  {
    name: 'Joe Kulveski',
    username: 'joekulveski',
    bgImg: links[0],
    avatar: avatars[0],
    unreadMessage: 0,
  },
  {
    name: 'Satin Darwin',
    username: 'satindarwin',
    bgImg: links[1],
    avatar: avatars[1],
    unreadMessage: 5,
  },
  {
    name: 'Krasinski Lahm',
    username: 'krasinski_lahm',
    bgImg: links[2],
    avatar: avatars[2],
    unreadMessage: 0,
  },
  {
    name: 'Diana Prince',
    username: 'diana_prince',
    bgImg: links[3],
    avatar: avatars[3],
    unreadMessage: 3,
  },
  {
    name: 'Kate Griffin',
    username: 'kategriffin12',
    bgImg: links[4],
    avatar: avatars[4],
    unreadMessage: 0,
  },
  {
    name: 'Joe Kulveski',
    username: 'joekulveski',
    bgImg: links[0],
    avatar: avatars[0],
    unreadMessage: 0,
  },
  {
    name: 'Satin Darwin',
    username: 'satindarwin',
    bgImg: links[1],
    avatar: avatars[1],
    unreadMessage: 5,
  },
  {
    name: 'Krasinski Lahm',
    username: 'krasinski_lahm',
    bgImg: links[2],
    avatar: avatars[2],
    unreadMessage: 0,
  },
  {
    name: 'Diana Prince',
    username: 'diana_prince',
    bgImg: links[3],
    avatar: avatars[3],
    unreadMessage: 3,
  },
  {
    name: 'Kate Griffin',
    username: 'kategriffin12',
    bgImg: links[4],
    avatar: avatars[4],
    unreadMessage: 0,
  },
  {
    name: 'Joe Kulveski',
    username: 'joekulveski',
    bgImg: links[0],
    avatar: avatars[0],
    unreadMessage: 0,
  },
  {
    name: 'Satin Darwin',
    username: 'satindarwin',
    bgImg: links[1],
    avatar: avatars[1],
    unreadMessage: 5,
  },
  {
    name: 'Krasinski Lahm',
    username: 'krasinski_lahm',
    bgImg: links[2],
    avatar: avatars[2],
    unreadMessage: 0,
  },
  {
    name: 'Diana Prince',
    username: 'diana_prince',
    bgImg: links[3],
    avatar: avatars[3],
    unreadMessage: 3,
  },
  {
    name: 'Kate Griffin',
    username: 'kategriffin12',
    bgImg: links[4],
    avatar: avatars[4],
    unreadMessage: 0,
  },
  {
    name: 'Kate Griffin',
    username: 'kategriffin12',
    bgImg: links[4],
    avatar: avatars[4],
    unreadMessage: 0,
  },
  {
    name: 'Joe Kulveski',
    username: 'joekulveski',
    bgImg: links[0],
    avatar: avatars[0],
    unreadMessage: 0,
  },
  {
    name: 'Satin Darwin',
    username: 'satindarwin',
    bgImg: links[1],
    avatar: avatars[1],
    unreadMessage: 5,
  },
  {
    name: 'Krasinski Lahm',
    username: 'krasinski_lahm',
    bgImg: links[2],
    avatar: avatars[2],
    unreadMessage: 0,
  },
  {
    name: 'Diana Prince',
    username: 'diana_prince',
    bgImg: links[3],
    avatar: avatars[3],
    unreadMessage: 3,
  },
  {
    name: 'Kate Griffin',
    username: 'kategriffin12',
    bgImg: links[4],
    avatar: avatars[4],
    unreadMessage: 0,
  },
  {
    name: 'Kate Griffin',
    username: 'kategriffin12',
    bgImg: links[4],
    avatar: avatars[4],
    unreadMessage: 0,
  },
  {
    name: 'Joe Kulveski',
    username: 'joekulveski',
    bgImg: links[0],
    avatar: avatars[0],
    unreadMessage: 0,
  },
  {
    name: 'Satin Darwin',
    username: 'satindarwin',
    bgImg: links[1],
    avatar: avatars[1],
    unreadMessage: 5,
  },
  {
    name: 'Krasinski Lahm',
    username: 'krasinski_lahm',
    bgImg: links[2],
    avatar: avatars[2],
    unreadMessage: 0,
  },
  {
    name: 'Diana Prince',
    username: 'diana_prince',
    bgImg: links[3],
    avatar: avatars[3],
    unreadMessage: 3,
  },
  {
    name: 'Kate Griffin',
    username: 'kategriffin12',
    bgImg: links[4],
    avatar: avatars[4],
    unreadMessage: 0,
  },
];
