import { links, avatars } from './imageLinks'
export const dummyUsers = [
  {
    name: 'Joe Kulveski',
    username: 'joekulveski',
    bgImg: links[0],
    avatar: avatars[0],
    unreadMessage: 0,
  },
  {
    name: 'Satin Darwin',
    username: 'satindarwin',
    bgImg: links[1],
    avatar: avatars[1],
    unreadMessage: 5,
  },
  {
    name: 'Krasinski Lahm',
    username: 'krasinski_lahm',
    bgImg: links[2],
    avatar: avatars[2],
    unreadMessage: 0,
  },
  {
    name: 'Diana Prince',
    username: 'diana_prince',
    bgImg: links[3],
    avatar: avatars[3],
    unreadMessage: 3,
  },
  {
    name: 'Kate Griffin',
    username: 'kategriffin12',
    bgImg: links[4],
    avatar: avatars[4],
    unreadMessage: 0,
  },
  {
    name: 'Joe Kulveski',
    username: 'joekulveski',
    bgImg: links[0],
    avatar: avatars[0],
    unreadMessage: 0,
  },
  {
    name: 'Satin Darwin',
    username: 'satindarwin',
    bgImg: links[1],
    avatar: avatars[1],
    unreadMessage: 5,
  },
  {
    name: 'Krasinski Lahm',
    username: 'krasinski_lahm',
    bgImg: links[2],
    avatar: avatars[2],
    unreadMessage: 0,
  },
  {
    name: 'Diana Prince',
    username: 'diana_prince',
    bgImg: links[3],
    avatar: avatars[3],
    unreadMessage: 3,
  },
  {
    name: 'Kate Griffin',
    username: 'kategriffin12',
    bgImg: links[4],
    avatar: avatars[4],
    unreadMessage: 0,
  },
  {
    name: 'Joe Kulveski',
    username: 'joekulveski',
    bgImg: links[0],
    avatar: avatars[0],
    unreadMessage: 0,
  },
  {
    name: 'Satin Darwin',
    username: 'satindarwin',
    bgImg: links[1],
    avatar: avatars[1],
    unreadMessage: 5,
  },
  {
    name: 'Krasinski Lahm',
    username: 'krasinski_lahm',
    bgImg: links[2],
    avatar: avatars[2],
    unreadMessage: 0,
  },
  {
    name: 'Diana Prince',
    username: 'diana_prince',
    bgImg: links[3],
    avatar: avatars[3],
    unreadMessage: 3,
  },
  {
    name: 'Kate Griffin',
    username: 'kategriffin12',
    bgImg: links[4],
    avatar: avatars[4],
    unreadMessage: 0,
  },
  {
    name: 'Kate Griffin',
    username: 'kategriffin12',
    bgImg: links[4],
    avatar: avatars[4],
    unreadMessage: 0,
  },
  {
    name: 'Joe Kulveski',
    username: 'joekulveski',
    bgImg: links[0],
    avatar: avatars[0],
    unreadMessage: 0,
  },
  {
    name: 'Satin Darwin',
    username: 'satindarwin',
    bgImg: links[1],
    avatar: avatars[1],
    unreadMessage: 5,
  },
  {
    name: 'Krasinski Lahm',
    username: 'krasinski_lahm',
    bgImg: links[2],
    avatar: avatars[2],
    unreadMessage: 0,
  },
  {
    name: 'Diana Prince',
    username: 'diana_prince',
    bgImg: links[3],
    avatar: avatars[3],
    unreadMessage: 3,
  },
  {
    name: 'Kate Griffin',
    username: 'kategriffin12',
    bgImg: links[4],
    avatar: avatars[4],
    unreadMessage: 0,
  },
  {
    name: 'Kate Griffin',
    username: 'kategriffin12',
    bgImg: links[4],
    avatar: avatars[4],
    unreadMessage: 0,
  },
  {
    name: 'Joe Kulveski',
    username: 'joekulveski',
    bgImg: links[0],
    avatar: avatars[0],
    unreadMessage: 0,
  },
  {
    name: 'Satin Darwin',
    username: 'satindarwin',
    bgImg: links[1],
    avatar: avatars[1],
    unreadMessage: 5,
  },
  {
    name: 'Krasinski Lahm',
    username: 'krasinski_lahm',
    bgImg: links[2],
    avatar: avatars[2],
    unreadMessage: 0,
  },
  {
    name: 'Diana Prince',
    username: 'diana_prince',
    bgImg: links[3],
    avatar: avatars[3],
    unreadMessage: 3,
  },
  {
    name: 'Kate Griffin',
    username: 'kategriffin12',
    bgImg: links[4],
    avatar: avatars[4],
    unreadMessage: 0,
  },
]

const data = [
  {
    user: {
      avatar: avatars[0],
      fullname: 'John Doe',
      username: 'johndoe',
    },
    content:
      'This is the first post on the mock figma design being created so enjoy the rest of the design. Get inspired the design will have amazing pictures from the unsplash plugin.',
    images: [
      'https://images.unsplash.com/photo-1509281373149-e957c6296406?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8cmFuZG9tfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
      'https://images.unsplash.com/photo-1507608616759-54f48f0af0ee?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fHJhbmRvbXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
      'https://images.unsplash.com/photo-1502230831726-fe5549140034?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fHJhbmRvbXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
    ],
  },
  {
    user: {
      avatar: avatars[0],
      fullname: 'John Doe',
      username: 'johndoe',
    },
    content:
      'This is the first post on the mock figma design being created so enjoy the rest of the design. Get inspired the design will have amazing pictures from the unsplash plugin.',
    images: [
      'https://images.unsplash.com/photo-1509281373149-e957c6296406?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8cmFuZG9tfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
    ],
  },
  {
    user: {
      avatar: avatars[0],
      fullname: 'John Doe',
      username: 'johndoe',
    },
    content:
      'This is the first post on the mock figma design being created so enjoy the rest of the design. Get inspired the design will have amazing pictures from the unsplash plugin.',
    images: [
      'https://images.unsplash.com/photo-1509281373149-e957c6296406?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8cmFuZG9tfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
      'https://images.unsplash.com/photo-1507608616759-54f48f0af0ee?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fHJhbmRvbXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
    ],
  },
  {
    user: {
      avatar: avatars[0],
      fullname: 'John Doe',
      username: 'johndoe',
    },
    content:
      'This is the first post on the mock figma design being created so enjoy the rest of the design. Get inspired the design will have amazing pictures from the unsplash plugin.',
    images: [
      'https://images.unsplash.com/photo-1509281373149-e957c6296406?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8cmFuZG9tfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
      'https://images.unsplash.com/photo-1507608616759-54f48f0af0ee?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fHJhbmRvbXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
      'https://images.unsplash.com/photo-1509281373149-e957c6296406?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8cmFuZG9tfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
      'https://images.unsplash.com/photo-1507608616759-54f48f0af0ee?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fHJhbmRvbXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
      'https://images.unsplash.com/photo-1507608616759-54f48f0af0ee?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fHJhbmRvbXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
    ],
  },
]
